apiVersion: apps/v1
kind: Deployment
metadata:
  name: beyza-lab
  namespace: beyza-lab
  labels:
    app: beyza-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beyza-lab
  template:
    metadata:
      labels:
        app: beyza-lab
    spec:
      containers:
        - name: beyza-lab
          image: ghcr.io/beyzakarasahann/deneme:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
