apiVersion: v1
kind: Service
metadata:
  name: atelier-site
  labels:
    app: atelier-site
spec:
  type: ClusterIP
  selector:
    app: atelier-site
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
